apiVersion: apps/v1
kind: Deployment
metadata:
  name: pago-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pago
  template:
    metadata:
      labels:
        app: pago
    spec:
      containers:
      - name: pago-container
        image: juan12311/pago:2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pago-service
spec:
  type: LoadBalancer
  selector:
    app: pago
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
