apiVersion: apps/v1
kind: Deployment
metadata:
  name: procesapago-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procesapago
  template:
    metadata:
      labels:
        app: procesapago
    spec:
      containers:
      - name: procesapago-container
        image: juan12311/procesapago:2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: procesapago-service
spec:
  type: ClusterIP
  selector:
    app: procesapago
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
